Fast HTTP Vulnerability Scanner: C:/fscan/HTTPCore/IoFunctions.h File Reference
C:/fscan/HTTPCore/IoFunctions.h File Reference
#include "HTTPCore.h"
Defines
#define MAX_CHECK_TIME_FOR_BW_UTILIZATION 200
#define CONN_TIMEOUT 10
#define READ_TIMEOUT 10
Functions
PHTTP_DATA ReadHTTPResponseData (STABLISHED_CONNECTION *conexion, PHTTP_DATA request, void *mutex)
This function reads an HTTP response stream from the remote webserver.
int SendHTTPRequestData (STABLISHED_CONNECTION *conexion, PHTTP_DATA request)
This function sends an HTTP request to the remote webserver. a CONEXION struct with initialized sockets. If the connection was previously initialized that struct will be resused.
int StablishConnection (STABLISHED_CONNECTION *connection)
This function stablishes a connection against a remote host.
int InitFileMapping (void)
int EndFileMapping (void)
char * DeleteFileMapping (void *ptr)
PHTTPIOMapping GetFileMapping (unsigned int DataSize, char *lpData)
Define Documentation
#define CONN_TIMEOUT 10
Definition at line 7 of file IoFunctions.h.
#define MAX_CHECK_TIME_FOR_BW_UTILIZATION 200
Definition at line 6 of file IoFunctions.h.
Referenced by LimitIOBandwidth().
#define READ_TIMEOUT 10
Definition at line 8 of file IoFunctions.h.
Referenced by ReadHTTPResponseData().
Function Documentation
char* DeleteFileMapping (void * ptr)
Definition at line 818 of file IoFunctions.cpp.
int EndFileMapping (void)
Definition at line 799 of file IoFunctions.cpp.
PHTTPIOMapping GetFileMapping (unsigned int DataSize, char * lpData)
Definition at line 862 of file IoFunctions.cpp.
Referenced by DecodeChunk(), and ReadHTTPResponseData().
int InitFileMapping (void)
Definition at line 792 of file IoFunctions.cpp.
PHTTP_DATA ReadHTTPResponseData (STABLISHED_CONNECTION * conexion, PHTTP_DATA request, void * lock)
This function reads an HTTP response stream from the remote webserver.
Parameters:
conexion struct returned by GetSocketConnection that includes the information of the remote host and valid socket.
request HTTP request that was sent before. This param is needed to resend the request
lock mutext used for exclusive access
Returns:
pointer to a HTTP_DATA Struct with the HTTP Response or NULL if the remote host can not be reached.
Definition at line 154 of file IoFunctions.cpp.
References _HTTPmapping_struct_::BufferedFileName, _HTTPmapping_struct_::BufferedPtr, BUFFSIZE, conexiones::BwLimit, conexiones::ConnectionAgainstProxy, _data::Data, _data::DataSize, conexiones::datasock, DWORD, FreeConnection(), GetFileMapping(), GetHeaderValue(), gettimeofday(), _data::Header, _data::HeaderSize, _HTTPmapping_struct_::hMapping, _HTTPmapping_struct_::hTmpFilename, InitHTTPData(), conexiones::io, LimitIOBandwidth(), conexiones::lock, LockMutex(), MAX_CHUNK_LENGTH, conexiones::NeedSSL, conexiones::NumberOfRequests, conexiones::PENDING_PIPELINE_REQUESTS, conexiones::PIPELINE_Request, READ_TIMEOUT, ReadHTTPResponseData(), RemovePipeLineRequest(), SendHTTPRequestData(), StablishConnection(), strnicmp, conexiones::tlastused, and UnLockMutex().
Referenced by ReadHTTPResponseData().
int SendHTTPRequestData (STABLISHED_CONNECTION * conexion, PHTTP_DATA request)
This function sends an HTTP request to the remote webserver. a CONEXION struct with initialized sockets. If the connection was previously initialized that struct will be resused.
Parameters:
conexion struct returned by GetSocketConnection that includes the information of the remote host and valid socket.
request HTTP request verbs and data to be delivered to the remote HTTP Server
Returns:
If there is no error, 1 is returned.
Note:
This Function only sends data, handling the responses from the HTTP server is done outside.
Definition at line 106 of file IoFunctions.cpp.
References _data::Data, _data::DataSize, conexiones::datasock, _data::Header, _data::HeaderSize, conexiones::NeedSSL, conexiones::port, and conexiones::targetDNS.
Referenced by FreeConnection(), and ReadHTTPResponseData().
int StablishConnection (STABLISHED_CONNECTION * connection)
This function stablishes a connection against a remote host.
Parameters:
connection CONEXION struct returned by a previous call to GetSocketConnection
Returns:
If the remote connection can be stablished, 1 is returned otherwise, an error is signaled with 0
Definition at line 699 of file IoFunctions.cpp.
Referenced by FreeConnection(), GetSocketConnection(), and ReadHTTPResponseData().