Fast HTTP Vulnerability Scanner: C:/fscan/HTTPCore/Threading.h File Reference
C:/fscan/HTTPCore/Threading.h File Reference
Functions
void LockMutex (void *mutex)
This function locks a mutex/critical Section object initialized by InitMutex().
void UnLockMutex (void *mutex)
This function unlocks a mutex/critical Section object.
void InitMutex (void *mutex)
This function Initializes a mutex/critical Section object.
void DeleteMutex (void *mutex)
This function deletes a previously initialized mutex/critical Section object.
Function Documentation
void DeleteMutex (void * mutex)
This function deletes a previously initialized mutex/critical Section object.
Parameters:
mutex pointer to a pthread_mutex_t under linux or to a Critical_Section under win32.
Note:
This function works under win32 and linux.
Definition at line 77 of file Threading.cpp.
void InitMutex (void * mutex)
This function Initializes a mutex/critical Section object.
Parameters:
mutex pointer to a pthread_mutex_t under linux or to a Critical_Section under win32.
Note:
This function works under win32 and linux.
Definition at line 60 of file Threading.cpp.
void LockMutex (void * mutex)
This function locks a mutex/critical Section object initialized by InitMutex().
Parameters:
mutex pointer to a pthread_mutex_t under linux or to a Critical_Section under win32.
Note:
This function works under win32 and linux.
Definition at line 24 of file Threading.cpp.
Referenced by GetSocketConnection(), HTTPCoreCancelHTTPRequest(), and ReadHTTPResponseData().
void UnLockMutex (void * mutex)
This function unlocks a mutex/critical Section object.
Parameters:
mutex pointer to a pthread_mutex_t under linux or to a Critical_Section under win32.
Note:
This function works under win32 and linux.
Definition at line 42 of file Threading.cpp.
Referenced by GetSocketConnection(), HTTPCoreCancelHTTPRequest(), and ReadHTTPResponseData().