Fast HTTP Vulnerability Scanner: C:/fscan/HTTPCore/Authentication/base64.cpp File Reference
C:/fscan/HTTPCore/Authentication/base64.cpp File Reference
#include "base64.h"
Defines
#define BAD -1
#define DECODE64(c) (isascii(c) ? base64val[c] : BAD)
Functions
unsigned int Base64EncodeGetLength (unsigned long size)
unsigned int Base64DecodeGetLength (unsigned long size)
int Base64Encode (unsigned char *out, const unsigned char *in, int inlen)
int Base64Decode (char *out, const char *in, unsigned long size)
Variables
static const char base64digits []
static const char base64val []
Define Documentation
#define BAD -1
Definition at line 43 of file base64.cpp.
Referenced by Base64Decode().
#define DECODE64 (c) (isascii(c) ? base64val[c] : BAD)
Definition at line 54 of file base64.cpp.
Referenced by Base64Decode().
Function Documentation
int Base64Decode (char * out, const char * in, unsigned long size)
Definition at line 100 of file base64.cpp.
References BAD, and DECODE64.
unsigned int Base64DecodeGetLength (unsigned long size)
Definition at line 21 of file base64.cpp.
References DWORD.
int Base64Encode (unsigned char * out, const unsigned char * in, int inlen)
Definition at line 58 of file base64.cpp.
References base64digits, and Base64EncodeGetLength().
Referenced by SendHttpRequest().
unsigned int Base64EncodeGetLength (unsigned long size)
Definition at line 8 of file base64.cpp.
References DWORD.
Referenced by Base64Encode().
Variable Documentation
const char base64digits[] [static]
Initial value:
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Definition at line 40 of file base64.cpp.
Referenced by Base64Encode().
const char base64val[] [static]
Initial value:
 {
     BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD,
     BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD,
     BAD,BAD,BAD,BAD, BAD,BAD,BAD,BAD, BAD,BAD,BAD, 62, BAD,BAD,BAD, 63,
      52, 53, 54, 55,  56, 57, 58, 59,  60, 61,BAD,BAD, BAD,BAD,BAD,BAD,
     BAD,  0,  1,  2,   3,  4,  5,  6,   7,  8,  9, 10,  11, 12, 13, 14,
      15, 16, 17, 18,  19, 20, 21, 22,  23, 24, 25,BAD, BAD,BAD,BAD,BAD,
     BAD, 26, 27, 28,  29, 30, 31, 32,  33, 34, 35, 36,  37, 38, 39, 40,
      41, 42, 43, 44,  45, 46, 47, 48,  49, 50, 51,BAD, BAD,BAD,BAD,BAD
 }
Definition at line 44 of file base64.cpp.