Fast HTTP Vulnerability Scanner: C:/fscan/HTTPCore/Authentication/base64.h File Reference
C:/fscan/HTTPCore/Authentication/base64.h File Reference
#include <ctype.h>
#include <stdio.h>
#include <assert.h>
#include <windows.h>
Defines
#define DWORD int
Functions
unsigned int Base64EncodeGetLength (unsigned long size)
unsigned int Base64DecodeGetLength (unsigned long size)
int Base64Encode (unsigned char *out, const unsigned char *in, int inlen)
int Base64Decode (char *out, const char *in, unsigned long size)
Define Documentation
#define DWORD int
Definition at line 12 of file base64.h.
Referenced by Base64DecodeGetLength(), Base64EncodeGetLength(), and ReadHTTPResponseData().
Function Documentation
int Base64Decode (char * out, const char * in, unsigned long size)
Definition at line 100 of file base64.cpp.
References BAD, and DECODE64.
unsigned int Base64DecodeGetLength (unsigned long size)
Definition at line 21 of file base64.cpp.
References DWORD.
int Base64Encode (unsigned char * out, const unsigned char * in, int inlen)
Definition at line 58 of file base64.cpp.
References base64digits, and Base64EncodeGetLength().
Referenced by SendHttpRequest().
unsigned int Base64EncodeGetLength (unsigned long size)
Definition at line 8 of file base64.cpp.
References DWORD.
Referenced by Base64Encode().