Fast HTTP Vulnerability Scanner: C:/fscan/HTTPCore/Authentication/ntlm.h File Reference
C:/fscan/HTTPCore/Authentication/ntlm.h File Reference
Data Structures
struct tSmbStrHeader
struct tSmbNtlmAuthRequest
struct tSmbNtlmAuthChallenge
struct tSmbNtlmAuthResponse
Defines
#define SmbLength(ptr) (((ptr)->buffer - (uint8*)(ptr)) + (ptr)->bufIndex)
Typedefs
typedef unsigned short uint16
typedef unsigned int uint32
typedef unsigned char uint8
Functions
void BuildAuthRequest (tSmbNtlmAuthRequest *request, long flags, char *host, char *domain)
void buildAuthResponse (tSmbNtlmAuthChallenge *challenge, tSmbNtlmAuthResponse *response, long flags, char *user, char *password, char *domain, char *host)
int from64tobits (char *out, const char *in)
void to64frombits (unsigned char *out, const unsigned char *in, int inlen)
void dumpAuthRequest (FILE *fp, tSmbNtlmAuthRequest *request)
void dumpAuthChallenge (FILE *fp, tSmbNtlmAuthChallenge *challenge)
void dumpAuthResponse (FILE *fp, tSmbNtlmAuthResponse *response)
Define Documentation
#define SmbLength (ptr) (((ptr)->buffer - (uint8*)(ptr)) + (ptr)->bufIndex)
Definition at line 142 of file ntlm.h.
Referenced by SendHttpRequest().
Typedef Documentation
typedef unsigned short uint16
Definition at line 70 of file ntlm.h.
typedef unsigned int uint32
Definition at line 71 of file ntlm.h.
typedef unsigned char uint8
Definition at line 72 of file ntlm.h.
Function Documentation
void BuildAuthRequest (tSmbNtlmAuthRequest * request, long flags, char * host, char * domain)
Definition at line 1217 of file ntlm.cpp.
Referenced by SendHttpRequest().
void buildAuthResponse (tSmbNtlmAuthChallenge * challenge, tSmbNtlmAuthResponse * response, long flags, char * user, char * password, char * domain, char * host)
Definition at line 1247 of file ntlm.cpp.
Referenced by SendHttpRequest().
void dumpAuthChallenge (FILE * fp, tSmbNtlmAuthChallenge * challenge)
void dumpAuthRequest (FILE * fp, tSmbNtlmAuthRequest * request)
void dumpAuthResponse (FILE * fp, tSmbNtlmAuthResponse * response)
int from64tobits (char * out, const char * in)
Definition at line 1401 of file ntlm.cpp.
Referenced by SendHttpRequest().
void to64frombits (unsigned char * out, const unsigned char * in, int inlen)
Definition at line 1375 of file ntlm.cpp.
Referenced by SendHttpRequest().